// rewrite-ui.js — writes plain-English UI component files
const fs = require('fs');
const path = require('path');

const BASE = path.resolve(__dirname, '..');

function w(rel, content) {
  fs.writeFileSync(path.join(BASE, rel), content, 'utf8');
  console.log('OK:', rel);
}

w('src/components/sidebar/AOISection.tsx', [
  "import { PenTool, Trash2, CheckCircle2 } from 'lucide-react';",
  "import { Button } from '../ui/button';",
  "import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card';",
  '',
  'interface AOISectionProps {',
  "  status: 'idle' | 'drawing' | 'complete';",
  '  vertices: number;',
  '  onStartDrawing: () => void;',
  '  onClear: () => void;',
  '}',
  '',
  'export function AOISection({ status, vertices, onStartDrawing, onClear }: AOISectionProps) {',
  '  return (',
  '    <section aria-labelledby="aoi-title">',
  '      <Card>',
  '        <CardHeader className="pb-3">',
  '          <CardTitle id="aoi-title" className="text-sm flex items-center gap-2">',
  '            <PenTool className="h-4 w-4" />',
  '            Study Area (Optional)',
  '          </CardTitle>',
  '          <CardDescription className="text-xs">',
  '            Draw a boundary on the map to mark your area of interest',
  '          </CardDescription>',
  '        </CardHeader>',
  '        <CardContent className="space-y-3">',
  "          {status === 'idle' && (",
  '            <Button onClick={onStartDrawing} className="w-full" aria-label="Start drawing boundary">',
  '              <PenTool className="h-4 w-4 mr-2" />',
  '              Draw Study Boundary',
  '            </Button>',
  '          )}',
  "          {status === 'drawing' && (",
  '            <div className="bg-primary/10 text-primary rounded-md p-3 text-sm">',
  '              <p className="font-medium">Drawing boundary\u2026</p>',
  '              <p className="text-xs mt-1">',
  '                Click on the map to add corners ({vertices} added)',
  '                <br />',
  '                Double-click to finish drawing',
  '              </p>',
  '            </div>',
  '          )}',
  "          {status === 'complete' && (",
  '            <div className="space-y-2">',
  '              <div className="bg-green-500/10 text-green-400 rounded-md p-3 text-sm flex items-start gap-2">',
  '                <CheckCircle2 className="h-4 w-4 mt-0.5 flex-shrink-0" />',
  '                <div>',
  '                  <p className="font-medium">Boundary Drawn</p>',
  '                  <p className="text-xs mt-1">{vertices} corner points</p>',
  '                </div>',
  '              </div>',
  '              <Button onClick={onClear} variant="outline" className="w-full" aria-label="Clear study boundary">',
  '                <Trash2 className="h-4 w-4 mr-2" />',
  '                Clear Boundary',
  '              </Button>',
  '            </div>',
  '          )}',
  '        </CardContent>',
  '      </Card>',
  '    </section>',
  '  );',
  '}',
].join('\n') + '\n');

w('src/components/sidebar/ResultsSection.tsx', [
  "import { BarChart3, Waves, GitBranch, Network } from 'lucide-react';",
  "import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card';",
  "import { Badge } from '../ui/badge';",
  '',
  'interface ResultsSectionProps {',
  '  nodesCount: number;',
  '  edgesCount: number;',
  '  componentsCount: number;',
  '}',
  '',
  'export function ResultsSection({ nodesCount, edgesCount, componentsCount }: ResultsSectionProps) {',
  '  return (',
  '    <section aria-labelledby="results-title">',
  '      <Card>',
  '        <CardHeader className="pb-3">',
  '          <CardTitle id="results-title" className="text-sm flex items-center gap-2">',
  '            <BarChart3 className="h-4 w-4" />',
  '            Analysis Summary',
  '          </CardTitle>',
  '          <CardDescription className="text-xs">Results from the last computation</CardDescription>',
  '        </CardHeader>',
  '        <CardContent>',
  '          <div className="space-y-3">',
  '            <div className="flex items-center justify-between p-2 rounded-md bg-muted/50">',
  '              <div className="flex items-center gap-2 text-sm">',
  '                <Waves className="h-4 w-4 text-muted-foreground" />',
  '                <span>Waterway sections</span>',
  '              </div>',
  '              <Badge variant="secondary">{nodesCount.toLocaleString()}</Badge>',
  '            </div>',
  '            <div className="flex items-center justify-between p-2 rounded-md bg-muted/50">',
  '              <div className="flex items-center gap-2 text-sm">',
  '                <GitBranch className="h-4 w-4 text-muted-foreground" />',
  '                <span>Connections mapped</span>',
  '              </div>',
  '              <Badge variant="secondary">{edgesCount.toLocaleString()}</Badge>',
  '            </div>',
  '            {componentsCount > 0 && (',
  '              <div className="flex items-center justify-between p-2 rounded-md bg-muted/50">',
  '                <div className="flex items-center gap-2 text-sm">',
  '                  <Network className="h-4 w-4 text-muted-foreground" />',
  '                  <span>Distinct networks</span>',
  '                </div>',
  '                <Badge variant="secondary">{componentsCount}</Badge>',
  '              </div>',
  '            )}',
  '          </div>',
  '        </CardContent>',
  '      </Card>',
  '    </section>',
  '  );',
  '}',
].join('\n') + '\n');
